version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
    environment:
      - NODE_ENV=production
    command: yarn dev
    depends_on:
      - db

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./web:/app
    environment:
      - NODE_ENV=development
    command: yarn dev
    depends_on:
      - db

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: growdev
      MYSQL_USER: root
      MYSQL_PASSWORD: example
    volumes:
      - ./mysql_data:/var/lib/mysql
